city_streets["anjttk"] = {builds: [
  {street: "Ванцетти", build: "4"},
  {street: "Ванцетти", build: "7"},
  {street: "Ванцетти", build: "5"},
  {street: "Ванцетти", build: "6"},
  {street: "Ватутина", build: "1а"},
  {street: "Ватутина", build: "25"},
  {street: "Ватутина", build: "1а"},
  {street: "Ватутина", build: "27"},
  {street: "Ватутина", build: "29"},
  {street: "Верный", build: "1"},
  {street: "Верный", build: "3"},
  {street: "Верный", build: "5"},
  {street: "Войкова", build: "3"},
  {street: "Войкова", build: "5"},
  {street: "Гагарина", build: "1"},
  {street: "Газовый", build: "1"},
  {street: "Газовый", build: "11"},
  {street: "Газовый", build: "13"},
  {street: "Газовый", build: "15"},
  {street: "Газовый", build: "17"},
  {street: "Газовый", build: "3"},
  {street: "Газовый", build: "5"},
  {street: "Газовый", build: "7"},
  {street: "Газовый", build: "9"},
  {street: "Желябова", build: "11"},
  {street: "Желябова", build: "13"},
  {street: "Желябова", build: "15"},
  {street: "Желябова", build: "17"},
  {street: "Желябова", build: "19"},
  {street: "Желябова", build: "3"},
  {street: "Желябова", build: "30"},
  {street: "Желябова", build: "32"},
  {street: "Желябова", build: "34"},
  {street: "Желябова", build: "36"},
  {street: "Желябова", build: "38"},
  {street: "Желябова", build: "3а"},
  {street: "Желябова", build: "3б"},
  {street: "Желябова", build: "5"},
  {street: "Желябова", build: "7"},
  {street: "Желябова", build: "7а"},
  {street: "Желябова", build: "9"},
  {street: "Желябова", build: "9а"},
  {street: "Заречная", build: "16"},
  {street: "им 137 Стрелковой Бригады", build: "1"},
  {street: "им 137 Стрелковой Бригады", build: "11"},
  {street: "им 137 Стрелковой Бригады", build: "3"},
  {street: "им 137 Стрелковой Бригады", build: "5"},
  {street: "им 137 Стрелковой Бригады", build: "9"},
  {street: "им 137 Стрелковой Бригады", build: "11"},
  {street: "им 137 Стрелковой Бригады", build: "5"},
  {street: "им 50-летия ВЛКСМ", build: "1"},
  {street: "им 50-летия ВЛКСМ", build: "3"},
  {street: "им 50-летия ВЛКСМ", build: "5"},
  {street: "им 50-летия Октября", build: "1"},
  {street: "им 50-летия Октября", build: "10"},
  {street: "им 50-летия Октября", build: "11"},
  {street: "им 50-летия Октября", build: "12"},
  {street: "им 50-летия Октября", build: "13"},
  {street: "им 50-летия Октября", build: "14"},
  {street: "им 50-летия Октября", build: "15"},
  {street: "им 50-летия Октября", build: "2"},
  {street: "им 50-летия Октября", build: "2а"},
  {street: "им 50-летия Октября", build: "3"},
  {street: "им 50-летия Октября", build: "4"},
  {street: "им 50-летия Октября", build: "5"},
  {street: "им 50-летия Октября", build: "6"},
  {street: "им 50-летия Октября", build: "6а"},
  {street: "им 50-летия Октября", build: "7"},
  {street: "им 50-летия Октября", build: "8"},
  {street: "им 50-летия Октября", build: "9"},
  {street: "К.Маркса", build: "10"},
  {street: "К.Маркса", build: "11"},
  {street: "К.Маркса", build: "12"},
  {street: "К.Маркса", build: "14"},
  {street: "К.Маркса", build: "16"},
  {street: "К.Маркса", build: "18а"},
  {street: "К.Маркса", build: "20"},
  {street: "К.Маркса", build: "22"},
  {street: "К.Маркса", build: "7"},
  {street: "К.Маркса", build: "7а"},
  {street: "К.Маркса", build: "8"},
  {street: "К.Маркса", build: "9"},
  {street: "Камышинская", build: "13"},
  {street: "Камышинская", build: "14"},
  {street: "Камышинская", build: "17"},
  {street: "Коммунальная", build: "35"},
  {street: "Коммунальная", build: "37"},
  {street: "Коммунальная", build: "41"},
  {street: "Крылова", build: "11"},
  {street: "Крылова", build: "13"},
  {street: "Крылова", build: "15"},
  {street: "Крылова", build: "17"},
  {street: "Крылова", build: "17а"},
  {street: "Крылова", build: "19"},
  {street: "Крылова", build: "21"},
  {street: "Крылова", build: "23"},
  {street: "Крылова", build: "25"},
  {street: "Крылова", build: "27"},
  {street: "Крылова", build: "29"},
  {street: "Крылова", build: "3"},
  {street: "Крылова", build: "7"},
  {street: "Крылова", build: "9"},
  {street: "Кубанская", build: "1"},
  {street: "Кубанская", build: "2"},
  {street: "Кубанская", build: "2а"},
  {street: "Кубанская", build: "4"},
  {street: "Кубанская", build: "6"},
  {street: "Лазо", build: "35"},
  {street: "Лазо", build: "17"},
  {street: "Лазо", build: "10"},
  {street: "Лазо", build: "12"},
  {street: "Лазо", build: "14"},
  {street: "Лазо", build: "18"},
  {street: "Лазо", build: "2"},
  {street: "Лазо", build: "20"},
  {street: "Лазо", build: "23"},
  {street: "Лазо", build: "24"},
  {street: "Лазо", build: "25"},
  {street: "Лазо", build: "26"},
  {street: "Лазо", build: "28"},
  {street: "Лазо", build: "29"},
  {street: "Лазо", build: "2а"},
  {street: "Лазо", build: "30"},
  {street: "Лазо", build: "31"},
  {street: "Лазо", build: "4"},
  {street: "Лазо", build: "6"},
  {street: "Лазо", build: "8"},
  {street: "Ленина", build: "12"},
  {street: "Ленина", build: "22"},
  {street: "Ленина", build: "24"},
  {street: "Ленина", build: "26"},
  {street: "Ленина", build: "28"},
  {street: "Ленина", build: "28а"},
  {street: "Ленина", build: "30"},
  {street: "Ленина", build: "30а"},
  {street: "Ленина", build: "32"},
  {street: "Ленина", build: "34"},
  {street: "Ленина", build: "36а"},
  {street: "Лизы Чайкиной", build: "50"},
  {street: "Ломоносова", build: "1"},
  {street: "Ломоносова", build: "1а"},
  {street: "Ломоносова", build: "3а"},
  {street: "Ломоносова", build: "4а"},
  {street: "Ломоносова", build: "5а"},
  {street: "Ломоносова", build: "6а"},
  {street: "М.Горького", build: "24"},
  {street: "М.Горького", build: "26"},
  {street: "М.Горького", build: "31"},
  {street: "М.Горького", build: "32"},
  {street: "М.Горького", build: "33 к.1"},
  {street: "М.Горького", build: "33 к.2"},
  {street: "М.Горького", build: "34"},
  {street: "М.Горького", build: "36"},
  {street: "М.Горького", build: "38"},
  {street: "М.Горького", build: "40"},
  {street: "М.Горького", build: "62а"},
  {street: "Матросова", build: "101"},
  {street: "Матросова", build: "103"},
  {street: "Матросова", build: "104"},
  {street: "Матросова", build: "105"},
  {street: "Матросова", build: "106"},
  {street: "Матросова", build: "108"},
  {street: "Матросова", build: "109"},
  {street: "Матросова", build: "110"},
  {street: "Матросова", build: "111"},
  {street: "Матросова", build: "112"},
  {street: "Матросова", build: "113"},
  {street: "Матросова", build: "114"},
  {street: "Матросова", build: "115"},
  {street: "Матросова", build: "117"},
  {street: "Матросова", build: "119"},
  {street: "Матросова", build: "121"},
  {street: "Матросова", build: "123"},
  {street: "Матросова", build: "125"},
  {street: "Матросова", build: "99"},
  {street: "Октябрьский", build: "1"},
  {street: "Октябрьский", build: "10"},
  {street: "Октябрьский", build: "11"},
  {street: "Октябрьский", build: "2"},
  {street: "Октябрьский", build: "4"},
  {street: "Октябрьский", build: "6"},
  {street: "Октябрьский", build: "8"},
  {street: "Перовской", build: "3"},
  {street: "Перовской", build: "30"},
  {street: "Перовской", build: "32"},
  {street: "Перовской", build: "5"},
  {street: "Перовской", build: "3"},
  {street: "Перовской", build: "30"},
  {street: "Перовской", build: "32"},
  {street: "Перовской", build: "5"},
  {street: "Просвещения", build: "201"},
  {street: "Просвещения", build: "215"},
  {street: "Просвещения", build: "219"},
  {street: "Просвещения", build: "176"},
  {street: "Просвещения", build: "176а"},
  {street: "Просвещения", build: "178"},
  {street: "Просвещения", build: "178а"},
  {street: "Просвещения", build: "180"},
  {street: "Просвещения", build: "227"},
  {street: "Профессиональный", build: "11"},
  {street: "Профессиональный", build: "13"},
  {street: "Профессиональный", build: "4"},
  {street: "Пушкина", build: "2"},
  {street: "Пушкина", build: "3"},
  {street: "Пушкина", build: "5"},
  {street: "Пушкина", build: "7"},
  {street: "Силовой", build: "26"},
  {street: "Силовой", build: "28"},
  {street: "Силовой", build: "30"},
  {street: "Силовой", build: "36"},
  {street: "Солнечная", build: "1"},
  {street: "Солнечная", build: "3"},
  {street: "Солнечная", build: "5"},
  {street: "Урицкого", build: "48"},
  {street: "Урицкого", build: "50"},
  {street: "Урицкого", build: "54"},
  {street: "Шоссейная", build: "1"},
  {street: "Шоссейная", build: "2"},
  {street: "Шоссейная", build: "4"},
  {street: "Электрический", build: "1"},
  {street: "Электрический", build: "7"},
  {street: "Электрический", build: "7а"}], streets: [{street: "Ванцетти"},
  {street: "Ватутина"},
  {street: "Верный"},
  {street: "Войкова"},
  {street: "Гагарина"},
  {street: "Газовый"},
  {street: "Желябова"},
  {street: "Заречная"},
  {street: "им 137 Стрелковой Бригады"},
  {street: "им 50-летия ВЛКСМ"},
  {street: "им 50-летия Октября"},
  {street: "К.Маркса"},
  {street: "Камышинская"},
  {street: "Коммунальная"},
  {street: "Крылова"},
  {street: "Кубанская"},
  {street: "Лазо"},
  {street: "Ленина"},
  {street: "Лизы Чайкиной"},
  {street: "Ломоносова"},
  {street: "М.Горького"},
  {street: "Матросова"},
  {street: "Октябрьский"},
  {street: "Перовской"},
  {street: "Просвещения"},
  {street: "Профессиональный"},
  {street: "Пушкина"},
  {street: "Силовой"},
  {street: "Солнечная"},
  {street: "Урицкого"},
  {street: "Шоссейная"},
  {street: "Электрический"}] };
