city_streets["belttk"] = {builds: [
  {street: "3-й", build: "1"},
  {street: "3-й", build: "10"},
  {street: "3-й", build: "11"},
  {street: "3-й", build: "12"},
  {street: "3-й", build: "13"},
  {street: "3-й", build: "14"},
  {street: "3-й", build: "15"},
  {street: "3-й", build: "16"},
  {street: "3-й", build: "17"},
  {street: "3-й", build: "18"},
  {street: "3-й", build: "19"},
  {street: "3-й", build: "2"},
  {street: "3-й", build: "20"},
  {street: "3-й", build: "23"},
  {street: "3-й", build: "24"},
  {street: "3-й", build: "25"},
  {street: "3-й", build: "26"},
  {street: "3-й", build: "3"},
  {street: "3-й", build: "4"},
  {street: "3-й", build: "5"},
  {street: "3-й", build: "6"},
  {street: "3-й", build: "65"},
  {street: "3-й", build: "67"},
  {street: "3-й", build: "68"},
  {street: "3-й", build: "69"},
  {street: "3-й", build: "7"},
  {street: "3-й", build: "70"},
  {street: "3-й", build: "71"},
  {street: "3-й", build: "72"},
  {street: "3-й", build: "73"},
  {street: "3-й", build: "74"},
  {street: "3-й", build: "75"},
  {street: "3-й", build: "76"},
  {street: "3-й", build: "77"},
  {street: "3-й", build: "78"},
  {street: "3-й", build: "79"},
  {street: "3-й", build: "8"},
  {street: "3-й", build: "80"},
  {street: "3-й", build: "81"},
  {street: "3-й", build: "82"},
  {street: "3-й", build: "83"},
  {street: "3-й", build: "84"},
  {street: "3-й", build: "86"},
  {street: "3-й", build: "9"},
  {street: "3-й", build: "93"},
  {street: "3-й", build: "93а"},
  {street: "3-й", build: "94"},
  {street: "3-й", build: "95"},
  {street: "3-й", build: "97"},
  {street: "3-й", build: "85"},
  {street: "3-й", build: "98"},
  {street: "6-й", build: "1"},
  {street: "Гражданская (Новый Городок)", build: "10"},
  {street: "Гражданская (Новый Городок)", build: "12"},
  {street: "Гражданская (Новый Городок)", build: "13"},
  {street: "Гражданская (Новый Городок)", build: "2"},
  {street: "Гражданская (Новый Городок)", build: "23"},
  {street: "Гражданская (Новый Городок)", build: "25"},
  {street: "Гражданская (Новый Городок)", build: "33"},
  {street: "Гражданская (Новый Городок)", build: "35"},
  {street: "Гражданская (Новый Городок)", build: "6"},
  {street: "Гражданская (Новый Городок)", build: "8"},
  {street: "Гражданская (Новый Городок)", build: "9"},
  {street: "Ермака", build: "21"},
  {street: "Железнодорожная", build: "15"},
  {street: "Железнодорожная", build: "17"},
  {street: "Железнодорожная", build: "21"},
  {street: "Железнодорожная", build: "23"},
  {street: "Железнодорожная", build: "32"},
  {street: "Железнодорожная", build: "40"},
  {street: "Железнодорожная", build: "54"},
  {street: "Железнодорожная", build: "56"},
  {street: "Киевская (Новый Городок)", build: "17"},
  {street: "Киевская (Новый Городок)", build: "39"},
  {street: "Киевская (Новый Городок)", build: "41"},
  {street: "Киевская (Новый Городок)", build: "43"},
  {street: "Киевская (Новый Городок)", build: "47"},
  {street: "Киевская (Новый Городок)", build: "49"},
  {street: "Киевская (Новый Городок)", build: "51"},
  {street: "Киевская (Новый Городок)", build: "53"},
  {street: "Киевская (Новый Городок)", build: "55"},
  {street: "Киевская (Новый Городок)", build: "57"},
  {street: "Киевская (Новый Городок)", build: "59"},
  {street: "Киевская (Новый Городок)", build: "61"},
  {street: "Ленина", build: "14"},
  {street: "Ленина", build: "14а"},
  {street: "Ленина", build: "17"},
  {street: "Ленина", build: "1б"},
  {street: "Ленина", build: "2"},
  {street: "Ленина", build: "28"},
  {street: "Ленина", build: "4"},
  {street: "Ленина", build: "41"},
  {street: "Ленина", build: "49"},
  {street: "Ленина", build: "6"},
  {street: "Ленина", build: "61"},
  {street: "Ленина", build: "67а"},
  {street: "Ленина", build: "8"},
  {street: "Ленина", build: "26"},
  {street: "Ленина", build: "67а"},
  {street: "Ленина", build: "8"},
  {street: "Маркса", build: "10"},
  {street: "Маркса", build: "12"},
  {street: "Маркса", build: "6"},
  {street: "Маркса", build: "8"},
  {street: "Московская", build: "4"},
  {street: "Московская", build: "6"},
  {street: "Октябрьская", build: "13"},
  {street: "Октябрьская", build: "15"},
  {street: "Октябрьская", build: "21"},
  {street: "Октябрьская", build: "23"},
  {street: "Октябрьская", build: "27"},
  {street: "Октябрьская", build: "29"},
  {street: "Октябрьская", build: "31"},
  {street: "Октябрьская", build: "35"},
  {street: "Октябрьская", build: "37"},
  {street: "Октябрьская", build: "39"},
  {street: "Октябрьская", build: "41"},
  {street: "Октябрьская", build: "47"},
  {street: "Октябрьская", build: "5"},
  {street: "Октябрьская", build: "51"},
  {street: "Октябрьская", build: "53"},
  {street: "Октябрьская", build: "55"},
  {street: "Октябрьская", build: "59 с 1 по 108кв НТВ"},
  {street: "Октябрьская", build: "63"},
  {street: "Октябрьская", build: "65"},
  {street: "Октябрьская", build: "7"},
  {street: "Почтовый", build: "8"},
  {street: "Пржевальского (Новый Городок)", build: "14"},
  {street: "Пржевальского (Новый Городок)", build: "17"},
  {street: "Пржевальского (Новый Городок)", build: "19"},
  {street: "Пржевальского (Новый Городок)", build: "20"},
  {street: "Седова (Новый Городок)", build: "34"},
  {street: "Седова (Новый Городок)", build: "36"},
  {street: "Седова (Новый Городок)", build: "40"},
  {street: "Седова (Новый Городок)", build: "48"},
  {street: "Седова (Новый Городок)", build: "50"},
  {street: "Седова (Новый Городок)", build: "52"},
  {street: "Седова (Новый Городок)", build: "54"},
  {street: "Седова (Новый Городок)", build: "58"},
  {street: "Седова (Новый Городок)", build: "60"},
  {street: "Советская", build: "13"},
  {street: "Советская", build: "17"},
  {street: "Советская", build: "26"},
  {street: "Советская", build: "32"},
  {street: "Советская", build: "33"},
  {street: "Советская", build: "35"},
  {street: "Советская", build: "36"},
  {street: "Советская", build: "37"},
  {street: "Советская", build: "38"},
  {street: "Советская", build: "39"},
  {street: "Советская", build: "40"},
  {street: "Советская", build: "42"},
  {street: "Советская", build: "43"},
  {street: "Советская", build: "45"},
  {street: "Советская", build: "46"},
  {street: "Советская", build: "48 Возможно подключение только активных абонентов ТТК"},
  {street: "Советская", build: "50"},
  {street: "Советская", build: "51"},
  {street: "Советская", build: "53"},
  {street: "Советская", build: "55"},
  {street: "Советская", build: "56"},
  {street: "Советская", build: "58"},
  {street: "Советская", build: "62"},
  {street: "Советская", build: "63"},
  {street: "Советская", build: "65"},
  {street: "Советская", build: "18"},
  {street: "Советская", build: "19"},
  {street: "Советская", build: "22"},
  {street: "Советская", build: "47"},
  {street: "Советская", build: "9"},
  {street: "Спортивный", build: "1"},
  {street: "Толстого", build: "10"},
  {street: "Толстого", build: "11"},
  {street: "Толстого", build: "12"},
  {street: "Толстого", build: "13"},
  {street: "Толстого", build: "14"},
  {street: "Толстого", build: "15 Возможно подключение только активных абонентов ТТК"},
  {street: "Толстого", build: "2"},
  {street: "Толстого", build: "6"},
  {street: "Толстого", build: "1"},
  {street: "Толстого", build: "9"},
  {street: "Тухачевского (Новый Городок)", build: "1"},
  {street: "Тухачевского (Новый Городок)", build: "10"},
  {street: "Тухачевского (Новый Городок)", build: "11"},
  {street: "Тухачевского (Новый Городок)", build: "13 Возможно подключение только активных абонентов ТТК"},
  {street: "Тухачевского (Новый Городок)", build: "2"},
  {street: "Тухачевского (Новый Городок)", build: "22"},
  {street: "Тухачевского (Новый Городок)", build: "3"},
  {street: "Тухачевского (Новый Городок)", build: "4"},
  {street: "Тухачевского (Новый Городок)", build: "5"},
  {street: "Тухачевского (Новый Городок)", build: "6"},
  {street: "Тухачевского (Новый Городок)", build: "7"},
  {street: "Тухачевского (Новый Городок)", build: "8"},
  {street: "Тухачевского (Новый Городок)", build: "9"},
  {street: "Цинкзаводской", build: "1"},
  {street: "Цинкзаводской", build: "11"},
  {street: "Цинкзаводской", build: "15"},
  {street: "Цинкзаводской", build: "3"},
  {street: "Цинкзаводской", build: "8"},
  {street: "Цинкзаводской", build: "13"},
  {street: "Цинкзаводской", build: "19"},
  {street: "Цинкзаводской", build: "6"},
  {street: "Цинкзаводской", build: "9"},
  {street: "Чкалова", build: "18"},
  {street: "Юбилейная", build: "10а"},
  {street: "Юбилейная", build: "13"},
  {street: "Юбилейная", build: "14"},
  {street: "Юбилейная", build: "15"},
  {street: "Юбилейная", build: "17"},
  {street: "Юбилейная", build: "18"},
  {street: "Юбилейная", build: "19"},
  {street: "Юбилейная", build: "4"},
  {street: "Юбилейная", build: "5"},
  {street: "Юбилейная", build: "6"},
  {street: "Юбилейная", build: "7"},
  {street: "Юбилейная", build: "9"},
  {street: "Юбилейная", build: "10"},
  {street: "Юбилейная", build: "12"},
  {street: "Юбилейная", build: "16"},
  {street: "Юбилейная", build: "8"},
  {street: "Юности", build: "11 2, 4, 5 подьезды НТВ"},
  {street: "Юности", build: "13_2, 3, 5 подьезды НТВ"},
  {street: "Юности", build: "15"},
  {street: "Юности", build: "20"},
  {street: "Юности", build: "21"},
  {street: "Юности", build: "22"},
  {street: "Юности", build: "5"},
  {street: "Юности", build: "7"},
  {street: "Юности", build: "8"},
  {street: "Юности", build: "9"},
  {street: "Юности", build: "14"},
  {street: "Юности", build: "24"}], streets: [{street: "3-й"},
  {street: "6-й"},
  {street: "Гражданская (Новый Городок)"},
  {street: "Ермака"},
  {street: "Железнодорожная"},
  {street: "Киевская (Новый Городок)"},
  {street: "Ленина"},
  {street: "Маркса"},
  {street: "Московская"},
  {street: "Октябрьская"},
  {street: "Почтовый"},
  {street: "Пржевальского (Новый Городок)"},
  {street: "Седова (Новый Городок)"},
  {street: "Советская"},
  {street: "Спортивный"},
  {street: "Толстого"},
  {street: "Тухачевского (Новый Городок)"},
  {street: "Цинкзаводской"},
  {street: "Чкалова"},
  {street: "Юбилейная"},
  {street: "Юности"}] };
