city_streets["berezovskij"] = {builds: [
  {street: "40 лет Октября ул", build: "22"},
  {street: "40 лет Октября ул", build: "24"},
  {street: "40 лет Победы ул", build: "4"},
  {street: "40 лет Победы ул", build: "6"},
  {street: "8 Марта ул", build: "1"},
  {street: "8 Марта ул", build: "10"},
  {street: "8 Марта ул", build: "12"},
  {street: "8 Марта ул", build: "2"},
  {street: "8 Марта ул", build: "3"},
  {street: "8 Марта ул", build: "4"},
  {street: "8 Марта ул", build: "5"},
  {street: "8 Марта ул", build: "6"},
  {street: "8 Марта ул", build: "8"},
  {street: "Волкова ул", build: "1"},
  {street: "Волкова ул", build: "10"},
  {street: "Волкова ул", build: "11"},
  {street: "Волкова ул", build: "12"},
  {street: "Волкова ул", build: "14"},
  {street: "Волкова ул", build: "16"},
  {street: "Волкова ул", build: "18"},
  {street: "Волкова ул", build: "1а"},
  {street: "Волкова ул", build: "2"},
  {street: "Волкова ул", build: "3"},
  {street: "Волкова ул", build: "4"},
  {street: "Волкова ул", build: "5"},
  {street: "Волкова ул", build: "6"},
  {street: "Волкова ул", build: "7"},
  {street: "Волкова ул", build: "8"},
  {street: "Волкова ул", build: "9"},
  {street: "Комсомольский б-р", build: "1"},
  {street: "Комсомольский б-р", build: "10"},
  {street: "Комсомольский б-р", build: "11"},
  {street: "Комсомольский б-р", build: "12"},
  {street: "Комсомольский б-р", build: "13"},
  {street: "Комсомольский б-р", build: "14"},
  {street: "Комсомольский б-р", build: "15"},
  {street: "Комсомольский б-р", build: "2"},
  {street: "Комсомольский б-р", build: "3"},
  {street: "Комсомольский б-р", build: "4"},
  {street: "Комсомольский б-р", build: "5"},
  {street: "Комсомольский б-р", build: "6"},
  {street: "Комсомольский б-р", build: "7"},
  {street: "Комсомольский б-р", build: "8"},
  {street: "Комсомольский б-р", build: "9"},
  {street: "Ленина пр-кт", build: "1"},
  {street: "Ленина пр-кт", build: "10"},
  {street: "Ленина пр-кт", build: "12"},
  {street: "Ленина пр-кт", build: "14"},
  {street: "Ленина пр-кт", build: "15"},
  {street: "Ленина пр-кт", build: "16"},
  {street: "Ленина пр-кт", build: "17"},
  {street: "Ленина пр-кт", build: "18"},
  {street: "Ленина пр-кт", build: "2"},
  {street: "Ленина пр-кт", build: "20"},
  {street: "Ленина пр-кт", build: "21"},
  {street: "Ленина пр-кт", build: "22"},
  {street: "Ленина пр-кт", build: "23"},
  {street: "Ленина пр-кт", build: "24"},
  {street: "Ленина пр-кт", build: "25а"},
  {street: "Ленина пр-кт", build: "26"},
  {street: "Ленина пр-кт", build: "26а"},
  {street: "Ленина пр-кт", build: "27"},
  {street: "Ленина пр-кт", build: "28"},
  {street: "Ленина пр-кт", build: "28а"},
  {street: "Ленина пр-кт", build: "29"},
  {street: "Ленина пр-кт", build: "3"},
  {street: "Ленина пр-кт", build: "30"},
  {street: "Ленина пр-кт", build: "31"},
  {street: "Ленина пр-кт", build: "32"},
  {street: "Ленина пр-кт", build: "33"},
  {street: "Ленина пр-кт", build: "34"},
  {street: "Ленина пр-кт", build: "35"},
  {street: "Ленина пр-кт", build: "36"},
  {street: "Ленина пр-кт", build: "37"},
  {street: "Ленина пр-кт", build: "38"},
  {street: "Ленина пр-кт", build: "4"},
  {street: "Ленина пр-кт", build: "40"},
  {street: "Ленина пр-кт", build: "41"},
  {street: "Ленина пр-кт", build: "44"},
  {street: "Ленина пр-кт", build: "46"},
  {street: "Ленина пр-кт", build: "48"},
  {street: "Ленина пр-кт", build: "5"},
  {street: "Ленина пр-кт", build: "50"},
  {street: "Ленина пр-кт", build: "52"},
  {street: "Ленина пр-кт", build: "53"},
  {street: "Ленина пр-кт", build: "54"},
  {street: "Ленина пр-кт", build: "56"},
  {street: "Ленина пр-кт", build: "58"},
  {street: "Ленина пр-кт", build: "5а"},
  {street: "Ленина пр-кт", build: "6"},
  {street: "Ленина пр-кт", build: "60"},
  {street: "Ленина пр-кт", build: "62"},
  {street: "Ленина пр-кт", build: "64"},
  {street: "Ленина пр-кт", build: "6а"},
  {street: "Ленина пр-кт", build: "7а"},
  {street: "Ленина пр-кт", build: "8"},
  {street: "Ленина пр-кт", build: "9"},
  {street: "Мира ул", build: "23"},
  {street: "Мира ул", build: "36"},
  {street: "Мира ул", build: "38"},
  {street: "Мира ул", build: "40"},
  {street: "Мира ул", build: "42"},
  {street: "Мира ул", build: "44"},
  {street: "Мира ул", build: "46"},
  {street: "Мира ул", build: "50"},
  {street: "Молодежный б-р", build: "1"},
  {street: "Молодежный б-р", build: "10"},
  {street: "Молодежный б-р", build: "11"},
  {street: "Молодежный б-р", build: "12"},
  {street: "Молодежный б-р", build: "13"},
  {street: "Молодежный б-р", build: "14"},
  {street: "Молодежный б-р", build: "15"},
  {street: "Молодежный б-р", build: "17"},
  {street: "Молодежный б-р", build: "2"},
  {street: "Молодежный б-р", build: "21"},
  {street: "Молодежный б-р", build: "23"},
  {street: "Молодежный б-р", build: "23а"},
  {street: "Молодежный б-р", build: "23б"},
  {street: "Молодежный б-р", build: "25"},
  {street: "Молодежный б-р", build: "3"},
  {street: "Молодежный б-р", build: "4"},
  {street: "Молодежный б-р", build: "5"},
  {street: "Молодежный б-р", build: "6"},
  {street: "Молодежный б-р", build: "7"},
  {street: "Молодежный б-р", build: "8"},
  {street: "Строителей ул", build: "1"},
  {street: "Строителей ул", build: "3"},
  {street: "Строителей ул", build: "5"},
  {street: "Строителей ул", build: "7"},
  {street: "Черняховского ул", build: "16"},
  {street: "Черняховского ул", build: "20"},
  {street: "Черняховского ул", build: "22"},
  {street: "Шахтеров пр-кт", build: "1"},
  {street: "Шахтеров пр-кт", build: "10"},
  {street: "Шахтеров пр-кт", build: "11"},
  {street: "Шахтеров пр-кт", build: "12"},
  {street: "Шахтеров пр-кт", build: "14"},
  {street: "Шахтеров пр-кт", build: "16б"},
  {street: "Шахтеров пр-кт", build: "17"},
  {street: "Шахтеров пр-кт", build: "2"},
  {street: "Шахтеров пр-кт", build: "21"},
  {street: "Шахтеров пр-кт", build: "25"},
  {street: "Шахтеров пр-кт", build: "25а"},
  {street: "Шахтеров пр-кт", build: "25б"},
  {street: "Шахтеров пр-кт", build: "25в"},
  {street: "Шахтеров пр-кт", build: "27"},
  {street: "Шахтеров пр-кт", build: "2а"},
  {street: "Шахтеров пр-кт", build: "3"},
  {street: "Шахтеров пр-кт", build: "6"},
  {street: "Шахтеров пр-кт", build: "8"},
  {street: "Шахтеров пр-кт", build: "9"}], streets: [{street: "﻿40 лет Октября ул"},
  {street: "40 лет Октября ул"},
  {street: "40 лет Победы ул"},
  {street: "8 Марта ул"},
  {street: "Волкова ул"},
  {street: "Комсомольский б-р"},
  {street: "Ленина пр-кт"},
  {street: "Мира ул"},
  {street: "Молодежный б-р"},
  {street: "Строителей ул"},
  {street: "Черняховского ул"},
  {street: "Шахтеров пр-кт"}] };
