city_streets["grttk"] = {builds: [
  {street: "60 лет Комсомола", build: "1"},
  {street: "60 лет Комсомола", build: "11"},
  {street: "60 лет Комсомола", build: "2"},
  {street: "60 лет Комсомола", build: "5"},
  {street: "60 лет Комсомола", build: "15"},
  {street: "60 лет Комсомола", build: "4"},
  {street: "60 лет Комсомола", build: "7"},
  {street: "60 лет Комсомола", build: "8"},
  {street: "Колмогоровская", build: "1а"},
  {street: "Колмогоровская", build: "1"},
  {street: "Колмогоровская", build: "10"},
  {street: "Колмогоровская", build: "11"},
  {street: "Колмогоровская", build: "12"},
  {street: "Колмогоровская", build: "13"},
  {street: "Колмогоровская", build: "14"},
  {street: "Колмогоровская", build: "15"},
  {street: "Колмогоровская", build: "17"},
  {street: "Колмогоровская", build: "18"},
  {street: "Колмогоровская", build: "19"},
  {street: "Колмогоровская", build: "2"},
  {street: "Колмогоровская", build: "20"},
  {street: "Колмогоровская", build: "21"},
  {street: "Колмогоровская", build: "22"},
  {street: "Колмогоровская", build: "24"},
  {street: "Колмогоровская", build: "26"},
  {street: "Колмогоровская", build: "28"},
  {street: "Колмогоровская", build: "3"},
  {street: "Колмогоровская", build: "32"},
  {street: "Колмогоровская", build: "36"},
  {street: "Колмогоровская", build: "38"},
  {street: "Колмогоровская", build: "5"},
  {street: "Колмогоровская", build: "9"},
  {street: "Профсоюзная", build: "1"},
  {street: "Профсоюзная", build: "5"},
  {street: "Светлая", build: "20"},
  {street: "Светлая", build: "23"},
  {street: "Светлая", build: "24"},
  {street: "Светлая", build: "26"},
  {street: "Светлая", build: "28"},
  {street: "Светлая", build: "32"},
  {street: "Светлая", build: "36"},
  {street: "Светлая", build: "10"},
  {street: "Светлая", build: "11"},
  {street: "Светлая", build: "12"},
  {street: "Светлая", build: "14"},
  {street: "Светлая", build: "15"},
  {street: "Светлая", build: "16"},
  {street: "Светлая", build: "17"},
  {street: "Светлая", build: "18"},
  {street: "Светлая", build: "19"},
  {street: "Светлая", build: "21"},
  {street: "Светлая", build: "22"},
  {street: "Светлая", build: "25"},
  {street: "Светлая", build: "3"},
  {street: "Светлая", build: "4"},
  {street: "Светлая", build: "5"},
  {street: "Светлая", build: "7"},
  {street: "Светлая", build: "9"}], streets: [{street: "60 лет Комсомола"},
  {street: "Колмогоровская"},
  {street: "Профсоюзная"},
  {street: "Светлая"}]};
