city_streets["gurttk"] = {builds: [
  {street: "30 лет Победы", build: "11"},
  {street: "30 лет Победы", build: "13 Возможно подключение только активных абонентов ТТК"},
  {street: "30 лет Победы", build: "15"},
  {street: "30 лет Победы", build: "2"},
  {street: "30 лет Победы", build: "36"},
  {street: "30 лет Победы", build: "4"},
  {street: "30 лет Победы", build: "40"},
  {street: "30 лет Победы", build: "42"},
  {street: "30 лет Победы", build: "44"},
  {street: "30 лет Победы", build: "46"},
  {street: "30 лет Победы", build: "5"},
  {street: "30 лет Победы", build: "64"},
  {street: "30 лет Победы", build: "7"},
  {street: "30 лет Победы", build: "76"},
  {street: "30 лет Победы", build: "78"},
  {street: "30 лет Победы", build: "17"},
  {street: "30 лет Победы", build: "17 к.1"},
  {street: "30 лет Победы", build: "66"},
  {street: "30 лет Победы", build: "68"},
  {street: "30 лет Победы", build: "70"},
  {street: "30 лет Победы", build: "72"},
  {street: "30 лет Победы", build: "74"},
  {street: "30 лет Победы", build: "9"},
  {street: "Автомобилистов", build: "1"},
  {street: "Дружбы", build: "10"},
  {street: "Дружбы", build: "2"},
  {street: "Дружбы", build: "4"},
  {street: "Дружбы", build: "6"},
  {street: "Дружбы", build: "8"},
  {street: "Кирова", build: "1"},
  {street: "Кирова", build: "2"},
  {street: "Кирова", build: "32"},
  {street: "Кирова", build: "35"},
  {street: "Кирова", build: "39"},
  {street: "Кирова", build: "43"},
  {street: "Кирова", build: "45"},
  {street: "Кирова", build: "49"},
  {street: "Кирова", build: "5"},
  {street: "Кирова", build: "52"},
  {street: "Кирова", build: "59"},
  {street: "Кирова", build: "61"},
  {street: "Кирова", build: "40"},
  {street: "Кирова", build: "42"},
  {street: "Кирова", build: "44"},
  {street: "Кирова", build: "46"},
  {street: "Кирова", build: "47"},
  {street: "Кирова", build: "48"},
  {street: "Кирова", build: "50"},
  {street: "Кирова", build: "55"},
  {street: "Коммунистическая", build: "14"},
  {street: "Коммунистическая", build: "16"},
  {street: "Ленина", build: "1"},
  {street: "Ленина", build: "101"},
  {street: "Ленина", build: "102"},
  {street: "Ленина", build: "105а"},
  {street: "Ленина", build: "3"},
  {street: "Ленина", build: "4"},
  {street: "Ленина", build: "5"},
  {street: "Ленина", build: "66"},
  {street: "Ленина", build: "83"},
  {street: "Ленина", build: "86"},
  {street: "Ленина", build: "91 Возможно подключение только активных абонентов ТТК"},
  {street: "Ленина", build: "97"},
  {street: "Ленина", build: "100"},
  {street: "Ленина", build: "103"},
  {street: "Ленина", build: "39"},
  {street: "Ленина", build: "41"},
  {street: "Ленина", build: "43"},
  {street: "Ленина", build: "45"},
  {street: "Ленина", build: "49"},
  {street: "Ленина", build: "51"},
  {street: "Ленина", build: "53"},
  {street: "Ленина", build: "55"},
  {street: "Ленина", build: "57"},
  {street: "Ленина", build: "59"},
  {street: "Ленина", build: "68"},
  {street: "Ленина", build: "69"},
  {street: "Ленина", build: "71"},
  {street: "Ленина", build: "73"},
  {street: "Ленина", build: "75"},
  {street: "Ленина", build: "76"},
  {street: "Ленина", build: "79"},
  {street: "Ленина", build: "87"},
  {street: "Ленина", build: "94"},
  {street: "Ленина", build: "96"},
  {street: "Ленина", build: "99"},
  {street: "Партизанская", build: "10"},
  {street: "Партизанская", build: "16"},
  {street: "Партизанская", build: "18"},
  {street: "Партизанская", build: "20а"},
  {street: "Партизанская", build: "49б"},
  {street: "Партизанская", build: "8"},
  {street: "Партизанская", build: "2"},
  {street: "Партизанская", build: "21"},
  {street: "Партизанская", build: "33"},
  {street: "Партизанская", build: "4"},
  {street: "Партизанская", build: "49"},
  {street: "Партизанская", build: "6"},
  {street: "Р.Люксембург", build: "65"},
  {street: "Чапаева", build: "4"},
  {street: "Чапаева", build: "6"},
  {street: "Чапаева", build: "8"},
  {street: "Щорса", build: "2"}], streets: [{street: "30 лет Победы"},
  {street: "Автомобилистов"},
  {street: "Дружбы"},
  {street: "Кирова"},
  {street: "Коммунистическая"},
  {street: "Ленина"},
  {street: "Партизанская"},
  {street: "Р.Люксембург"},
  {street: "Чапаева"},
  {street: "Щорса"}] };
