city_streets["inskttk"] = {builds: [
  {street: "Дунаевского", build: "4"},
  {street: "Ильича", build: "12"},
  {street: "Ильича", build: "19"},
  {street: "Ильича", build: "21"},
  {street: "Ильича", build: "23"},
  {street: "Ильича", build: "27"},
  {street: "Ильича", build: "29"},
  {street: "Ильича", build: "31"},
  {street: "Ильича", build: "33"},
  {street: "Ильича", build: "37"},
  {street: "Ильича", build: "47"},
  {street: "Парковая", build: "1"},
  {street: "Приморская", build: "10"},
  {street: "Приморская", build: "14"},
  {street: "Приморская", build: "15"},
  {street: "Приморская", build: "16"},
  {street: "Приморская", build: "25"},
  {street: "Приморская", build: "7"},
  {street: "Пугачева", build: "2"},
  {street: "Пугачева", build: "4"},
  {street: "Пугачева", build: "6"},
  {street: "Чистопольская", build: "15"},
  {street: "Энергетическая", build: "14"},
  {street: "Энергетическая", build: "16"},
  {street: "Энергетическая", build: "18"},
  {street: "Энергетическая", build: "20"},
  {street: "Энергетическая", build: "22"}], streets: [{street: "Дунаевского"},
  {street: "Ильича"},
  {street: "Парковая"},
  {street: "Приморская"},
  {street: "Пугачева"},
  {street: "Чистопольская"},
  {street: "Энергетическая"}] };
