city_streets["len"] = {builds: [
  {street: "Васильева ул", build: "12"},
  {street: "Васильева ул", build: "14"},
  {street: "Григорченкова ул", build: "1"},
  {street: "Григорченкова ул", build: "3"},
  {street: "Григорченкова ул", build: "31"},
  {street: "Григорченкова ул", build: "31а"},
  {street: "Григорченкова ул", build: "51"},
  {street: "Григорченкова ул", build: "53"},
  {street: "Зварыгина ул", build: "10"},
  {street: "Зварыгина ул", build: "10а"},
  {street: "Зварыгина ул", build: "12"},
  {street: "Зварыгина ул", build: "14"},
  {street: "Зварыгина ул", build: "15"},
  {street: "Зварыгина ул", build: "16"},
  {street: "Зварыгина ул", build: "16а"},
  {street: "Зварыгина ул", build: "18"},
  {street: "Зварыгина ул", build: "2"},
  {street: "Зварыгина ул", build: "20"},
  {street: "Зварыгина ул", build: "22"},
  {street: "Зварыгина ул", build: "5"},
  {street: "Зварыгина ул", build: "8"},
  {street: "Зварыгина ул", build: "8а"},
  {street: "Кирова пр-кт", build: "100"},
  {street: "Кирова пр-кт", build: "100а"},
  {street: "Кирова пр-кт", build: "100б"},
  {street: "Кирова пр-кт", build: "102"},
  {street: "Кирова пр-кт", build: "108"},
  {street: "Кирова пр-кт", build: "108а"},
  {street: "Кирова пр-кт", build: "108б"},
  {street: "Кирова пр-кт", build: "110"},
  {street: "Кирова пр-кт", build: "112"},
  {street: "Кирова пр-кт", build: "114"},
  {street: "Кирова пр-кт", build: "116"},
  {street: "Кирова пр-кт", build: "118"},
  {street: "Кирова пр-кт", build: "120"},
  {street: "Кирова пр-кт", build: "122"},
  {street: "Кирова пр-кт", build: "124"},
  {street: "Кирова пр-кт", build: "126"},
  {street: "Кирова пр-кт", build: "32"},
  {street: "Кирова пр-кт", build: "34б"},
  {street: "Кирова пр-кт", build: "39а"},
  {street: "Кирова пр-кт", build: "52"},
  {street: "Кирова пр-кт", build: "58"},
  {street: "Кирова пр-кт", build: "60"},
  {street: "Кирова пр-кт", build: "62"},
  {street: "Кирова пр-кт", build: "67"},
  {street: "Кирова пр-кт", build: "69"},
  {street: "Кирова пр-кт", build: "71"},
  {street: "Кирова пр-кт", build: "71а"},
  {street: "Кирова пр-кт", build: "75"},
  {street: "Кирова пр-кт", build: "75а"},
  {street: "Кирова пр-кт", build: "77"},
  {street: "Кирова пр-кт", build: "79"},
  {street: "Кирова пр-кт", build: "79а"},
  {street: "Кирова пр-кт", build: "81"},
  {street: "Кирова пр-кт", build: "83"},
  {street: "Кирова пр-кт", build: "83а"},
  {street: "Кирова пр-кт", build: "87"},
  {street: "Кирова пр-кт", build: "87а"},
  {street: "Кирова пр-кт", build: "88"},
  {street: "Кирова пр-кт", build: "88а"},
  {street: "Кирова пр-кт", build: "89"},
  {street: "Кирова пр-кт", build: "90"},
  {street: "Кирова пр-кт", build: "90а"},
  {street: "Кирова пр-кт", build: "91"},
  {street: "Кирова пр-кт", build: "92"},
  {street: "Кирова пр-кт", build: "93"},
  {street: "Кирова пр-кт", build: "93а"},
  {street: "Кирова пр-кт", build: "96"},
  {street: "Кирова пр-кт", build: "98"},
  {street: "Клюева б-р", build: "3"},
  {street: "Клюева б-р", build: "4"},
  {street: "Клюева б-р", build: "5 к.1"},
  {street: "Кузбасская ул", build: "112 к.1"},
  {street: "Кузбасская ул", build: "114 к.1"},
  {street: "Кольчугинский пр-кт", build: "3"},
  {street: "Кольчугинский пр-кт", build: "5"},
  {street: "Кольчугинский пр-кт", build: "5 к.3"},
  {street: "Крупина пер", build: "29"},
  {street: "Крупина пер", build: "29а"},
  {street: "Ленина пр-кт", build: "1"},
  {street: "Ленина пр-кт", build: "13а"},
  {street: "Ленина пр-кт", build: "17"},
  {street: "Ленина пр-кт", build: "19"},
  {street: "Ленина пр-кт", build: "21"},
  {street: "Ленина пр-кт", build: "28"},
  {street: "Ленина пр-кт", build: "29"},
  {street: "Ленина пр-кт", build: "3"},
  {street: "Ленина пр-кт", build: "30"},
  {street: "Ленина пр-кт", build: "31"},
  {street: "Ленина пр-кт", build: "4"},
  {street: "Ленина пр-кт", build: "41"},
  {street: "Ленина пр-кт", build: "43б"},
  {street: "Ленина пр-кт", build: "53 к.1"},
  {street: "Ленина пр-кт", build: "53 к.2"},
  {street: "Ленина пр-кт", build: "53 к.3"},
  {street: "Ленина пр-кт", build: "53а"},
  {street: "Ленина пр-кт", build: "55 к.1"},
  {street: "Ленина пр-кт", build: "57 к.1"},
  {street: "Ленина пр-кт", build: "57 к.3"},
  {street: "Ленина пр-кт", build: "57б"},
  {street: "Ленина пр-кт", build: "59 к.1"},
  {street: "Ленина пр-кт", build: "59 к.2"},
  {street: "Ленина пр-кт", build: "59 к.3"},
  {street: "Ленина пр-кт", build: "6"},
  {street: "Ленина пр-кт", build: "61 к.1"},
  {street: "Ленина пр-кт", build: "63 к.2"},
  {street: "Ленина пр-кт", build: "63 к.3"},
  {street: "Ленина пр-кт", build: "63 к.4"},
  {street: "Ленина пр-кт", build: "65"},
  {street: "Ленина пр-кт", build: "67 к.1"},
  {street: "Ленина пр-кт", build: "67 к.2"},
  {street: "Ленина пр-кт", build: "67 к.3"},
  {street: "Ленина пр-кт", build: "67 к.4"},
  {street: "Ленина пр-кт", build: "69"},
  {street: "Ленина пр-кт", build: "71"},
  {street: "Ленина пр-кт", build: "75 к.2"},
  {street: "Ленина пр-кт", build: "76а"},
  {street: "Ленина пр-кт", build: "78"},
  {street: "Ленина пр-кт", build: "80"},
  {street: "Ленина пр-кт", build: "80а"},
  {street: "Ленина пр-кт", build: "82"},
  {street: "Ленина пр-кт", build: "82 к.1"},
  {street: "Ленина пр-кт", build: "84"},
  {street: "Ленина пр-кт", build: "86"},
  {street: "Ленина пр-кт", build: "88"},
  {street: "Ленина пр-кт", build: "88 к.2"},
  {street: "Ленина пр-кт", build: "90 к.1"},
  {street: "Ленина пр-кт", build: "90 к.2"},
  {street: "Ломоносова ул", build: "1"},
  {street: "Ломоносова ул", build: "2"},
  {street: "Пушкина ул", build: "1"},
  {street: "Пушкина ул", build: "10"},
  {street: "Пушкина ул", build: "11"},
  {street: "Пушкина ул", build: "11а"},
  {street: "Пушкина ул", build: "12"},
  {street: "Пушкина ул", build: "13"},
  {street: "Пушкина ул", build: "14"},
  {street: "Пушкина ул", build: "15"},
  {street: "Пушкина ул", build: "19"},
  {street: "Пушкина ул", build: "19а"},
  {street: "Пушкина ул", build: "1а"},
  {street: "Пушкина ул", build: "2"},
  {street: "Пушкина ул", build: "21"},
  {street: "Пушкина ул", build: "3"},
  {street: "Пушкина ул", build: "4"},
  {street: "Пушкина ул", build: "5"},
  {street: "Пушкина ул", build: "6"},
  {street: "Пушкина ул", build: "68"},
  {street: "Пушкина ул", build: "70"},
  {street: "Пушкина ул", build: "72"},
  {street: "Пушкина ул", build: "8"},
  {street: "Пушкина ул", build: "80"},
  {street: "Пушкина ул", build: "82"},
  {street: "Пушкина ул", build: "88"},
  {street: "Розы Люксембург ул", build: "21"},
  {street: "Розы Люксембург ул", build: "37"},
  {street: "Розы Люксембург ул", build: "39"},
  {street: "Розы Люксембург ул", build: "41"},
  {street: "Розы Люксембург ул", build: "43"},
  {street: "Розы Люксембург ул", build: "47"},
  {street: "Спасстанция ул", build: "2а"},
  {street: "Спасстанция ул", build: "30"},
  {street: "Спасстанция ул", build: "6"},
  {street: "Суворова ул", build: "10"},
  {street: "Суворова ул", build: "12 к.1"},
  {street: "Суворова ул", build: "12 к.2"},
  {street: "Суворова ул", build: "12а"},
  {street: "Суворова ул", build: "14"},
  {street: "Суворова ул", build: "16"},
  {street: "Суворова ул", build: "5"},
  {street: "Суворова ул", build: "6"},
  {street: "Суворова ул", build: "7"},
  {street: "Суворова ул", build: "8"},
  {street: "Суворова ул", build: "9"},
  {street: "Текстильщиков пр-кт", build: "1 к.1"},
  {street: "Текстильщиков пр-кт", build: "10"},
  {street: "Текстильщиков пр-кт", build: "11 к.1"},
  {street: "Текстильщиков пр-кт", build: "11 к.2"},
  {street: "Текстильщиков пр-кт", build: "12"},
  {street: "Текстильщиков пр-кт", build: "14 к.1"},
  {street: "Текстильщиков пр-кт", build: "14 к.2"},
  {street: "Текстильщиков пр-кт", build: "14 к.3"},
  {street: "Текстильщиков пр-кт", build: "2 к.1"},
  {street: "Текстильщиков пр-кт", build: "3 к.1"},
  {street: "Текстильщиков пр-кт", build: "3 к.2"},
  {street: "Текстильщиков пр-кт", build: "4 к.1"},
  {street: "Текстильщиков пр-кт", build: "4 к.2"},
  {street: "Текстильщиков пр-кт", build: "4 к.4"},
  {street: "Текстильщиков пр-кт", build: "5 к.1"},
  {street: "Текстильщиков пр-кт", build: "6 к.1"},
  {street: "Текстильщиков пр-кт", build: "7 к.1"},
  {street: "Текстильщиков пр-кт", build: "7 к.2"},
  {street: "Текстильщиков пр-кт", build: "7 к.3"},
  {street: "Текстильщиков пр-кт", build: "7 к.4"},
  {street: "Текстильщиков пр-кт", build: "8 к.1"},
  {street: "Текстильщиков пр-кт", build: "9 к.1"},
  {street: "Текстильщиков пр-кт", build: "9 к.2"},
  {street: "Текстильщиков пр-кт", build: "9 к.3"},
  {street: "Текстильщиков пр-кт", build: "9 к.4"},
  {street: "Телефонная ул", build: "13"},
  {street: "Топкинская ул", build: "10 к.1"},
  {street: "Топкинская ул", build: "10 к.2"},
  {street: "Топкинская ул", build: "14"},
  {street: "Топкинская ул", build: "16"},
  {street: "Топкинская ул", build: "18"},
  {street: "Топкинская ул", build: "6 к.1"},
  {street: "Топкинская ул", build: "6 к.2"},
  {street: "Топкинская ул", build: "6 к.3"},
  {street: "Туснолобовой ул", build: "27"},
  {street: "Туснолобовой ул", build: "29"},
  {street: "Туснолобовой ул", build: "31"},
  {street: "Ульяновская ул", build: "3"},
  {street: "Ульяновская ул", build: "4"},
  {street: "Химиков б-р", build: "10 к.1"},
  {street: "Химиков б-р", build: "10 к.2"},
  {street: "Химиков б-р", build: "10 к.3"},
  {street: "Химиков б-р", build: "12"},
  {street: "Химиков б-р", build: "3"},
  {street: "Химиков б-р", build: "3 к.1"},
  {street: "Химиков б-р", build: "4"},
  {street: "Химиков б-р", build: "5"},
  {street: "Химиков б-р", build: "6"},
  {street: "Химиков б-р", build: "7"},
  {street: "Химиков б-р", build: "7 к.2а"},
  {street: "Химиков б-р", build: "7 к.2б"},
  {street: "Химиков б-р", build: "7 к.2в"},
  {street: "Химиков б-р", build: "7 к.3"},
  {street: "Химиков б-р", build: "7 к.4"},
  {street: "Химиков б-р", build: "8 к.1"},
  {street: "Химиков б-р", build: "9 к.1"},
  {street: "Химиков б-р", build: "9 к.2"},
  {street: "Химиков б-р", build: "9 к.3"},
  {street: "Шевцовой ул", build: "1"},
  {street: "Шевцовой ул", build: "10"},
  {street: "Шевцовой ул", build: "3"},
  {street: "Шевцовой ул", build: "8"},
  {street: "Шевцовой ул", build: "9"},
  {street: "Шишлянникова ул", build: "14"},
  {street: "Юргинская ул", build: "10"},
  {street: "Юргинская ул", build: "14"},
  {street: "Юргинская ул", build: "4 к.1"},
  {street: "Юргинская ул", build: "4 к.2"},
  {street: "Юргинская ул", build: "6"},
  {street: "Юргинская ул", build: "8"}], streets: [{street: "﻿Васильева ул"},
  {street: "Васильева ул"},
  {street: "Григорченкова ул"},
  {street: "Зварыгина ул"},
  {street: "Кирова пр-кт"},
  {street: "Клюева б-р"},
  {street: "Кузбасская ул"},
  {street: "Кольчугинский пр-кт"},
  {street: "Крупина пер"},
  {street: "Ленина пр-кт"},
  {street: "Ломоносова ул"},
  {street: "Пушкина ул"},
  {street: "Розы Люксембург ул"},
  {street: "Спасстанция ул"},
  {street: "Суворова ул"},
  {street: "Текстильщиков пр-кт"},
  {street: "Телефонная ул"},
  {street: "Топкинская ул"},
  {street: "Туснолобовой ул"},
  {street: "Ульяновская ул"},
  {street: "Химиков б-р"},
  {street: "Шевцовой ул"},
  {street: "Шишлянникова ул"},
  {street: "Юргинская ул"}] };
