city_streets["pls"] = {builds: [
  {street: "Автодорожная ул", build: "29"},
  {street: "Бажова ул", build: "3"},
  {street: "Бажова ул", build: "5"},
  {street: "Бажова ул", build: "7"},
  {street: "Бакинская ул", build: "1"},
  {street: "Бакинская ул", build: "14"},
  {street: "Бакинская ул", build: "16"},
  {street: "Бакинская ул", build: "18"},
  {street: "Бакинская ул", build: "1а"},
  {street: "Бакинская ул", build: "3"},
  {street: "Бакинская ул", build: "3а"},
  {street: "Бакинская ул", build: "6"},
  {street: "Бакинская ул", build: "8"},
  {street: "Волжская ул", build: "13"},
  {street: "Волжская ул", build: "13а"},
  {street: "Волжская ул", build: "15"},
  {street: "Волжская ул", build: "3"},
  {street: "Иркутская ул", build: "4а"},
  {street: "Космонавтов ул", build: "61"},
  {street: "Космонавтов ул", build: "62"},
  {street: "Космонавтов ул", build: "63"},
  {street: "Космонавтов ул", build: "65"},
  {street: "Космонавтов ул", build: "65а"},
  {street: "Космонавтов ул", build: "67"},
  {street: "Космонавтов ул", build: "68"},
  {street: "Космонавтов ул", build: "71"},
  {street: "Космонавтов ул", build: "73"},
  {street: "Космонавтов ул", build: "75"},
  {street: "Космонавтов ул", build: "77 к.1"},
  {street: "Космонавтов ул", build: "77 к.2"},
  {street: "Космонавтов ул", build: "77 к.3"},
  {street: "Космонавтов ул", build: "77а"},
  {street: "Космонавтов ул", build: "78"},
  {street: "Космонавтов ул", build: "80"},
  {street: "Космонавтов ул", build: "82"},
  {street: "Космонавтов ул", build: "82а"},
  {street: "Космонавтов ул", build: "84"},
  {street: "Космонавтов ул", build: "88"},
  {street: "Космонавтов ул", build: "88а"},
  {street: "Космонавтов ул", build: "90"},
  {street: "Космонавтов ул", build: "90а"},
  {street: "Космонавтов ул", build: "92"},
  {street: "Космонавтов ул", build: "92а"},
  {street: "Космонавтов ул", build: "94"},
  {street: "Космонавтов ул", build: "94 к.1"},
  {street: "Крупской ул", build: "108"},
  {street: "Крупской ул", build: "110"},
  {street: "Крупской ул", build: "112"},
  {street: "Крупской ул", build: "114"},
  {street: "Крупской ул", build: "116"},
  {street: "Крупской ул", build: "118"},
  {street: "Крупской ул", build: "126"},
  {street: "Крупской ул", build: "130"},
  {street: "Молодежная ул", build: "17"},
  {street: "Молодежная ул", build: "19"},
  {street: "Молодежная ул", build: "31"},
  {street: "Молодогвардейцев ул", build: "24"},
  {street: "Молодогвардейцев ул", build: "26"},
  {street: "Молодогвардейцев ул", build: "28"},
  {street: "Молодогвардейцев ул", build: "30"},
  {street: "Республиканская ул", build: "1"},
  {street: "Республиканская ул", build: "11"},
  {street: "Республиканская ул", build: "2"},
  {street: "Республиканская ул", build: "3"},
  {street: "Республиканская ул", build: "4"},
  {street: "Республиканская ул", build: "6"},
  {street: "Республиканская ул", build: "9"},
  {street: "Читинская ул", build: "35"},
  {street: "Читинская ул", build: "37"},
  {street: "Читинская ул", build: "39"},
  {street: "Читинская ул", build: "39а"},
  {street: "Читинская ул", build: "41"},
  {street: "Шукшина ул", build: "25"},
  {street: "Шукшина ул", build: "27"},
  {street: "Шукшина ул", build: "29"},
  {street: "Шукшина ул", build: "30"},
  {street: "Шукшина ул", build: "31"},
  {street: "Шукшина ул", build: "32"},
  {street: "Шукшина ул", build: "33"},
  {street: "Шукшина ул", build: "36"}], streets: [
  {street: "Автодорожная ул"},
  {street: "Бажова ул"},
  {street: "Бакинская ул"},
  {street: "Волжская ул"},
  {street: "Иркутская ул"},
  {street: "Космонавтов ул"},
  {street: "Крупской ул"},
  {street: "Молодежная ул"},
  {street: "Молодогвардейцев ул"},
  {street: "Республиканская ул"},
  {street: "Читинская ул"},
  {street: "Шукшина ул"}] };
