city_streets["topkittk"] = {builds: [
  {street: "Дзержинского", build: "3"},
  {street: "Дзержинского", build: "7"},
  {street: "Дзержинского", build: "9"},
  {street: "Красная Горка", build: "1"},
  {street: "Красная Горка", build: "10"},
  {street: "Красная Горка", build: "11"},
  {street: "Красная Горка", build: "12"},
  {street: "Красная Горка", build: "13"},
  {street: "Красная Горка", build: "14 Возможно подключение только активных абонентов ТТК"},
  {street: "Красная Горка", build: "15"},
  {street: "Красная Горка", build: "16"},
  {street: "Красная Горка", build: "19"},
  {street: "Красная Горка", build: "2"},
  {street: "Красная Горка", build: "20"},
  {street: "Красная Горка", build: "21"},
  {street: "Красная Горка", build: "23"},
  {street: "Красная Горка", build: "24"},
  {street: "Красная Горка", build: "26"},
  {street: "Красная Горка", build: "27"},
  {street: "Красная Горка", build: "3"},
  {street: "Красная Горка", build: "4"},
  {street: "Красная Горка", build: "7"},
  {street: "Красная Горка", build: "8"},
  {street: "Красная Горка", build: "9"},
  {street: "Кузнецкая", build: "10"},
  {street: "Кузнецкая", build: "12"},
  {street: "Кузнецкая", build: "3 2ой подьезд НТВ"},
  {street: "Кузнецкая", build: "5"},
  {street: "Кузнецкая", build: "6"},
  {street: "Кузнецкая", build: "8 Возможно подключение только активных абонентов ТТК"},
  {street: "Ленина", build: "151"},
  {street: "Лермонтова", build: "1"},
  {street: "Лермонтова", build: "1а"},
  {street: "Лермонтова", build: "2"},
  {street: "Лермонтова", build: "2а Возможно подключение только активных абонентов ТТК"},
  {street: "Лермонтова", build: "3"},
  {street: "Лермонтова", build: "4"},
  {street: "Луначарского", build: "1"},
  {street: "Луначарского", build: "10"},
  {street: "Луначарского", build: "11"},
  {street: "Луначарского", build: "2"},
  {street: "Луначарского", build: "2а"},
  {street: "Луначарского", build: "3"},
  {street: "Луначарского", build: "4"},
  {street: "Луначарского", build: "5"},
  {street: "Луначарского", build: "7"},
  {street: "Луначарского", build: "8"},
  {street: "Луначарского", build: "9"},
  {street: "Революции", build: "11"},
  {street: "Революции", build: "16"},
  {street: "Революции", build: "30"},
  {street: "Революции", build: "32"},
  {street: "Революции", build: "7"},
  {street: "Революции", build: "9"},
  {street: "Солнечный", build: "1"},
  {street: "Солнечный", build: "11"},
  {street: "Солнечный", build: "12"},
  {street: "Солнечный", build: "17"},
  {street: "Солнечный", build: "19"},
  {street: "Солнечный", build: "19а"},
  {street: "Солнечный", build: "19б"},
  {street: "Солнечный", build: "2"},
  {street: "Солнечный", build: "2а Возможно подключение только активных абонентов ТТК"},
  {street: "Солнечный", build: "23а"},
  {street: "Солнечный", build: "23б"},
  {street: "Солнечный", build: "24а"},
  {street: "Солнечный", build: "24б"},
  {street: "Солнечный", build: "25б"},
  {street: "Солнечный", build: "26"},
  {street: "Солнечный", build: "27"},
  {street: "Солнечный", build: "27а"},
  {street: "Солнечный", build: "28"},
  {street: "Солнечный", build: "29"},
  {street: "Солнечный", build: "29а"},
  {street: "Солнечный", build: "29б"},
  {street: "Солнечный", build: "3"},
  {street: "Солнечный", build: "30"},
  {street: "Солнечный", build: "30а"},
  {street: "Солнечный", build: "30б"},
  {street: "Солнечный", build: "3а"},
  {street: "Солнечный", build: "4"},
  {street: "Солнечный", build: "4а Возможно подключение только активных абонентов ТТК"},
  {street: "Солнечный", build: "4б"},
  {street: "Солнечный", build: "5"},
  {street: "Солнечный", build: "7"},
  {street: "Солнечный", build: "8"},
  {street: "Солнечный", build: "8а"},
  {street: "Солнечный", build: "9"},
  {street: "Топкинская", build: "21"},
  {street: "Топкинская", build: "23"},
  {street: "Топкинская", build: "25"},
  {street: "Топкинская", build: "27"},
  {street: "Топкинская", build: "6"}], streets: [{street: "Дзержинского"},
  {street: "Красная Горка"},
  {street: "Кузнецкая"},
  {street: "Ленина"},
  {street: "Лермонтова"},
  {street: "Луначарского"},
  {street: "Революции"},
  {street: "Топкинская"},
  {street: "Солнечный"}] };
